export const users = [
  {
    name: "Tommy Tom",
    phone: 8325678323,
    img: "https://randomuser.me/api/portraits/men/32.jpg",
    address: "Sector 20 Gurugram, Haryana",
    message: "Hello!!",
  },
  {
    name: "Sacha Grafin",
    phone: 8170569235,
    img: "https://randomuser.me/api/portraits/women/44.jpg",
    address: "Sector 20 Gurugram, Haryana",
    message: "Hello!!",
  },
  {
    name: "Tommy Tom",
    phone: 9325678323,
    img: "https://randomuser.me/api/portraits/men/62.jpg",
    address: "Sector 20 Gurugram, Haryana",
    message: "Hello!!",
  },
  {
    name: "Tommy Tom",
    phone: 8825678323,
    img: "https://randomuser.me/api/portraits/women/12.jpg",
    address: "Sector 20 Gurugram, Haryana",
    message: "Hello!!",
  },
  {
    name: "Tommy Tom",
    phone: 983256783,
    img: "https://randomuser.me/api/portraits/women/52.jpg",
    address: "Sector 20 Gurugram, Haryana",
    message: "Hello!!",
  },
  {
    name: "Tommy Tom",
    phone: 7325678323,
    img: "https://randomuser.me/api/portraits/men/37.jpg",
    address: "Sector 20 Gurugram, Haryana",
    message: "Hello!!",
  },
  {
    name: "Tommy Tom",
    phone: 86325678321,
    img: "https://randomuser.me/api/portraits/men/30.jpg",
    address: "Sector 20 Gurugram, Haryana",
    message: "Hello!!",
  },
];
